### ISSUE TITLE
More examples

### ISSUE THREAD

**Issue by Neo-X** [CyberZHG/keras-layer-normalization#2]
It would help to have a few more examples of how to use this layer. Maybe an example that includes the use of an LSTM, which the method was created for.

**Comment by CyberZHG** [comment]
The repo was created for transformer:

https://github.com/CyberZHG/keras-transformer/blob/088c1842f19f520a6bc6314c239cabb1e742ee7c/keras_transformer/transformer.py#L42-L45

**Comment by Neo-X** [comment]
Okay. It would be wonderful to have a few small standalone examples. This is not a high priority, I already figured it out but could be helpful for the next person.
